#!/usr/bin/env python
import sys
import os
import glob

if __name__ == '__main__':
	if len(sys.argv) <= 2:
		print("Usage: %s <file to convert to jpg> <opt_size>" % sys.argv[0])
		exit(-1)
        print glob.glob(sys.argv[1])
        for filename in glob.glob(sys.argv[1]):
	    name, ext = os.path.splitext(filename)
	    os.system("sips -s format jpeg %s; mv %s %s.jpg" % (filename, filename, name))
            if len(sys.argv) == 3:
                os.system("sips --setProperty formatOptions normal -Z %s %s.jpg" % (sys.argv[2], name))

